load:
  description: 加载网易云音乐歌单音乐列表
  fields:
    id:
      name: 歌单ID
      description: 参数介绍【https://github.com/shaonianzhentan/ha_cloud_music/tree/master/custom_components/ha_cloud_music】
      example: '258244'
      selector:
        text:
    type:
      name: 音乐类型
      description: 网易歌单(playlist)、网易电台(djradio)、喜马拉雅专辑(ximalaya)
      example: 'ximalaya'
      selector:
        text:
    index:
      name: 要从第几首开始播放
      description: 要从第几首开始播放（如果超过列表总数量则从第1首开始播放）
      example: '1'
      selector:
        text:
pick:
  description: 通过歌名点歌
  fields:
    name:
      name: 歌曲名称
      description: 歌曲名称
      example: '万有引力'
      selector:
        text:
config:
  description: 配置修改（可单独设置）
  fields:
    is_voice:
      name: 启用语音识别
      description: （禁用/启用）语音识别（0：禁用，1：启用）
      example: 1
      selector:
        text:
    is_notify:
      name: 启用通知
      description: （禁用/启用）通知（0：禁用，1：启用）
      example: 1
      selector:
        text:
    play_mode:
      name: 播放模式
      description: 播放模式（0：列表循环，1：顺序播放，2：随机播放，3：单曲循环）
      example: 1
      selector:
        number:
          min: 0
          max: 4
          step: 1
          mode: slider
    media_rate:
      name: 播放速度
      description: 注意：播放速度只支持内置VLC（1为正常速度）
      example: 1
      selector:
        number:
          min: 1
          max: 3
          step: 0.5
          mode: slider
    tts_mode:
      name: TTS声音模式
      description: TTS声音模式（1：标准男声，2：标准女声，3：情感男声，4：情感女声）
      example: 4
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider
    tts_volume:
      name: TTS音量
      description: TTS音量（1到100）
      example: 50
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
tts:
  description: 文字转语音
  fields:
    message:
      name: 要播放的文字
      description: 要播放的文字(支持内置模板格式)
      example: '现在的时间是{{now().strftime("%H:%M")}}'
      selector:
        text:
cache:
  description: 缓存音乐文件
  fields:
    name:
      name: mp3文件名称
      description: mp3文件名称
      example: '不会用就别乱调用，可能会把系统搞卡死'
      selector:
        text:
    url:
      name: mp3音乐链接
      description: mp3音乐链接
      example: '不会用千万别乱调用，可能会把系统搞卡死崩溃'
      selector:
        text: