load:
  description: 加载网易云音乐歌单音乐列表
  fields:
    id:
      description: 参数介绍【https://github.com/shaonianzhentan/ha_cloud_music/tree/master/custom_components/ha_cloud_music】
      example: '258244'
    type:
      description: 网易歌单(playlist)、网易电台(djradio)、喜马拉雅专辑(ximalaya)
      example: 'ximalaya'
    index:
      description: 要从第几首开始播放（如果超过列表总数量则从第1首开始播放）
      example: '1'
pick:
  description: 通过歌名点歌
  fields:
    name:
      description: 歌曲名称
      example: '万有引力'
config:
  description: 配置修改（可单独设置）
  fields:
    is_voice:
      description: （禁用/启用）语音识别（0：禁用，1：启用）
      example: 1
    is_notify:
      description: （禁用/启用）通知（0：禁用，1：启用）
      example: 1
    is_debug:
      description: （禁用/启用）调试（0：禁用，1：启用）
      example: 1
    play_mode:
      description: 播放模式（0：列表循环，1：顺序播放，2：随机播放，3：单曲循环）
      example: 1
    tts_mode:
      description: TTS声音模式（1：标准男声，2：标准女声，3：情感男声，4：情感女声）
      example: 4
    tts_volume:
      description: TTS音量（1到100）
      example: 50
tts:
  description: 文字转语音
  fields:
    message:
      description: 要播放的文字(支持内置模板格式)
      example: '现在的时间是{{now().strftime("%H:%M")}}'
tts_clear:
  description: 清除文字转语音的缓存
web_media_player_updated:
  description: 和网页播放器通信时使用，请勿手动调用